### ISSUE TITLE
Tab Navigation Icon Should Be Pressable

### ISSUE THREAD

**Issue by mylesdomingo** [calblueprint/alemany#35]
The icon on the tab navigation does not trigger a navigate call. Tapping on the navigation bar requires the user to tap on the text to navigate to the next screen. If a user taps the icon, nothing happens. 

Idea: try removing the `Pressable` wrapper in `Icon.tsx`, I believe this overwrites the actual navigate() call.

**Comment by kennethlien** [comment]
We'd probably have to wrap `Icon` with our own component. Will try this
